typography_spectrum: 0.1534399390220642
color:
  brandStrength: 0.3957000633236021
  lightness: 0.34946965030394495
  saturation: 0.814732220955193
  rhythmicContrast: 0.6380655358079821
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
opengraph:
  image: null
  appId: www.facebook.com/alden.morriscyr
layout_spectrum: 0.3803823401685804
author:
  name: Alden Morris
  email: photos@aldenmorris.com
  url: ''
name: Photographie Immobilière Rive-Sud
